### ISSUE TITLE
Peer review

### ISSUE THREAD

**Issue by raindew18** [Junbo345/Homeless#2]
### **Opening Statement Summary**
I am peer-reviewing the paper from Felix Li. This paper talks about the homeless population in Toronto and the effectiveness of relevant city policies.

### **Strong positive points**

- A clear structure, following the minds is easy. 

- Discussion with city policy.

### **Critical Improvements Needed**

- Averaged quarterly data may not always be nice replacement for monthly data. Think about the weather in Toronto, the homeless people are greatly affected by it. It might be a good idea if also looking at monthly data, or the weather factor.

- You may mention more about your work of eliminating the challenge of measuring accurate data, for example, on the cleaning data part.

- The definition of working age is not clear enough. Some citations or more convincing resources are optional.

### **Suggestions for Improvement**

- More suggestion and analysis of city policies. Comparing Toronto with other policies is a good idea, Maybe just some more? Such as refugee policies.

- The results are clear, but some explanation could make it better. It is interesting to know the population of working-age homeless people is increasing, what might be the reason behind?

### **Evaluation**
Structure is clear and focused, it's a nice paper. Maybe write some more with more graphs.
85/100

**Comment by Junbo345** [comment]
Thank you for your thoughtful review of my paper. I appreciate your positive feedback on the structure and the discussion regarding city policy.

Regarding the concerns about the age categorization, I have modified the definition of "working age" to clarify it further. However, due to time constraints, I am unable to address all the other suggestions like avering data. 

I understand the importance of these points and will consider them for future revisions. Thank you again for your valuable insights!
